project:
  type: website

website:
  open-graph: true
  title: "PatientExperience-QDC website"
  description: "Website for the NHS England funded Patient Experience Qualitative Data Categorisation project"
  site-url: https://CDU-data-science-team.github.io/PatientExperience-QDC
  favicon: docs/_assets/favicon.ico
  repo-url: https://github.com/CDU-data-science-team/PatientExperience-QDC
  repo-actions: [issue]

  page-footer:
    left: "This page is built with [Quarto](https://quarto.org/) and is based on the [NHS Theme by Craig Shenton](https://github.com/craig-shenton/quarto-nhs-theme)"
    right:
    - text: "License"
      href: https://github.com/CDU-data-science-team/PatientExperience-QDC/blob/main/LICENCE
    - text: "Code of Conduct"
      href: https://github.com/CDU-data-science-team/PatientExperience-QDC/blob/main/CODE_OF_CONDUCT.md

  navbar:
    background: light
    title: false
    collapse-below: lg
    left:
      - text: "About PatientExperience-QDC"
        icon: "book"
        href: index.qmd
      - text: "Updates"
        icon: "rss"
        href: updates.qmd

    right:
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/CDU-data-science-team/PatientExperience-QDC/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/CDU-data-science-team/PatientExperience-QDC/discussions"
      - icon: github
        href: https://github.com/CDU-data-science-team/PatientExperience-QDC
        aria-label: GitHub

  sidebar:
    id: toc-side
    style: "floating"
    pinned: true
    contents:
      - text: "Homepage"
        file: index.qmd
      - text: "Background and roadmap"
        file: background.qmd
      - section: Qualitative Framework
        file: framework/index.qmd
        contents:
          - auto: framework/*.qmd
      - section: Machine learning (pxtextmining)
        file: pxtextmining/index.qmd
        contents:
          - pxtextmining/performance_metrics.qmd
          - pxtextmining/model_selection.qmd
      - section: Experiences dashboard
        file: dashboard/index.qmd
        contents:
          - auto: dashboard/*.qmd
      - text: "Acknowledgements"
        file: acknowledgements.qmd
  comments:
    giscus:
      repo: CDU-data-science-team/PatientExperience-QDC
format:
  html:
    toc: true
    toc-depth: 4
    theme:
      light: [cosmo, _assets/style/theme.scss]
    code-copy: true
    code-overflow: wrap
    css: _assets/style/styles.css
    include-after-body: _assets/style/js.html

execute:
  freeze: auto
